### ISSUE TITLE
Review plugin API

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard-agent#131]
We need to review the plugin management with the following requisites:

- Load code out of project.
- Hot unload.
- Explicit loading through `temboard.plugins` option.
- Fail on inexistant plugin in configuration.
- First-class configuration : configuration section and validation, loading from envvar. cf. #44 
- Plugin check installation : postgres version, SELinux enforce, whatever. Check can raise an incompatible error, gracefully handled by agent. 
- Ability to enable debug messages of a plugin.

## Proposition

- Add `--debug=temboardagent,mypkg`
- Use setuptools entrypoint
- Use a simple Python class:
  ``` python
  class TemboardAgentPlugin(object):
    def __init__(self, app):
        app.config.add_spec(OptionSpec())
        self.app = app
    def load(self):
        self.app.routes.add('GET', ...)
    def reload(self):
        pass
    def unload(self):
        self.app.routes.remove(...)
  ```

### TODO

- [x] load plugin from entrypoint
- [x] Document new plugins REST API
- [x] Extend configuration analyze
- [x] reload configuration on SIGHUP
- [x] hot load/unload plugin
- [x] propagate application reload on all processes
- [x] Migrate hellong
- [x] Migrate activty
- [x] Migrate administration
- [x] Migrate dashboard
- [x] Migrate monitoring
- [x] Migrate pgconf
- [x] Implement `remove_route`
- [x] read `temboard-agent.conf.d`
- [x] Implement `remove_specs`
- [x] Migrate dashboard
- [x] Implement activity.unload
- [x] Implement hellong.unload
- [x] Implément `remove_worker`
- [x] Implément `TaskManager.shutdown`
- [x] Test it

cc @julmon

**Comment by bersace** [comment]
Done.
